networks:
  web-app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${APP_NAME}APP"
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/php.ini
    networks:
      - web-app-network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: "${APP_NAME}WEBSERVER"
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d
    ports:
      - "30000:80"
    networks:
      - web-app-network
    depends_on:
      - app

  db:
    image: mysql:8.4
    restart: unless-stopped
    container_name: "${APP_NAME}DB"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/:/docker-entrypoint-initdb.d
    ports:
      - "30001:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - web-app-network

volumes:
  mysql_data:
